config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    member do
      post :comment
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project

  around_create :track_comment

  def track_comment
    transaction do
      Event.create(project: project, user: user, details: "#{user.email} says #{content}")
      yield
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :nullify
  has_many :comments, dependent: :destroy

  def update_tracked(params, user)
    assign_attributes(params)
    if status_changed?
      self.events.build(user: user, details: "Status changed from #{status_was.humanize} to #{status.humanize}")
    end
    update(params)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy comment ]
  before_action :authenticate_user!

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update_tracked(project_params, current_user)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # POST /projects/1/comments
  def comment
    @project.comments.build(user: current_user, content: comment_params[:content])

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :status)
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>User:</strong>
    <%= event.user_id %>
  </p>

  <p>
    <strong>Details:</strong>
    <%= event.details %>
  </p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_comment.html.erb
<%= form_with(model: comment, url: comment_project_path(project)) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= project.status %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project.user_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

<h2>Leave a comment</h2>
<%= render "comment", comment: @project.comments.new, project: @project %>

<h2>History</h2>
<%= render @project.events %>